---
apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.component_id }}-${{ values.user }}-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${{ values.destination }}